"""empty message

Revision ID: 1a194e7f65d8
Revises: 1e662fc655e6
Create Date: 2020-04-11 01:51:39.500922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a194e7f65d8'
down_revision = '1e662fc655e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'biography',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='This stores bio of user',
               existing_nullable=True)
    op.alter_column('profiles', 'date_joined',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='This stores data joined of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='This stores email of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='This stores first name of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'gender',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='This stores gender of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='This stores the identification (unique of a user)',
               autoincrement=True)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='This stores last name of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'location',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='This stores location of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'profile_picture',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='This stores profile picture of a user',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'profile_picture',
               existing_type=sa.VARCHAR(length=100),
               comment='This stores profile picture of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'location',
               existing_type=sa.VARCHAR(length=100),
               comment='This stores location of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment='This stores last name of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'id',
               existing_type=sa.INTEGER(),
               comment='This stores the identification (unique of a user)',
               autoincrement=True)
    op.alter_column('profiles', 'gender',
               existing_type=sa.VARCHAR(length=20),
               comment='This stores gender of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment='This stores first name of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment='This stores email of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'date_joined',
               existing_type=sa.VARCHAR(length=100),
               comment='This stores data joined of a user',
               existing_nullable=True)
    op.alter_column('profiles', 'biography',
               existing_type=sa.TEXT(),
               comment='This stores bio of user',
               existing_nullable=True)
    # ### end Alembic commands ###
