"""empty message

Revision ID: 734db62451e5
Revises: 
Create Date: 2020-04-11 01:07:17.934641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734db62451e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='This stores unique identification of a user',
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'id',
               existing_type=sa.INTEGER(),
               comment='This stores unique identification of a user',
               autoincrement=True)
    # ### end Alembic commands ###
